version: '3.8'
services:
  cine:
    image: image_name
    ports:
      - "8001:80"
    networks:
      - cine-front
  db:
    image: mysql:8.0.1
    environment:
      MYSQL_ROOT_PASSWORD: i20213tn004
      MYSQL_DATABASE: cines
      MYSQL_USER: cines
      MYSQL_PASSWORD: gpds2024
    ports:
      - "8003:3306"
    networks:
      - cine-net
